### ISSUE TITLE
Errors while trying to download 

### ISSUE THREAD

**Issue by shivamdev-lgtm** [borzunov/bit-torrent#7]
I ran the following command
`./torrent_cli.py show debian-mac-9.8.0-amd64-netinst.iso.torrent`
But got this error:

```
Traceback (most recent call last):
  File "./torrent_cli.py", line 202, in <module>
    sys.exit(main())
  File "./torrent_cli.py", line 196, in main
    arguments.func(arguments)
  File "./torrent_cli.py", line 68, in show_handler
    formatters.format_title(torrent_info, True) + formatters.format_content(torrent_info))
  File "/home/sjha022002/bit-torrent/torrent_client/control/formatters.py", line 18, in format_title
    lines = ['Name: {}\n'.format(info.suggested_name)]
AttributeError: 'TorrentInfo' object has no attribute 'suggested_name'
```

**Comment by borzunov** [comment]
Thanks for pointing this out and sorry for the late response!

I've fixed the bug in 98aacb87baed6f326878817b83b41d1580ff6f67.
